name: United Agency
tagline: Social & Digital Marketing Agency, London
description: United are a social media and digital agency based on Tottenham Court Road in central London. We deliver social media and digital strategies for clients including websites, community management, mobile apps, social advertising and analytics.
markdown: redcarpet
pygments: true

url: http://unitedagency.github.io
baseurl: /

exclude: ['bower_components', 'node_modules']